<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Andorra', 'code' => 'AD', 'dialing_code' => '+376'],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'dialing_code' => '+971'],
            ['name' => 'Afghanistan', 'code' => 'AF', 'dialing_code' => '+93'],
            ['name' => 'Anguilla', 'code' => 'AI', 'dialing_code' => '+1264'],
            ['name' => 'Albania', 'code' => 'AL', 'dialing_code' => '+355'],
            ['name' => 'Armenia', 'code' => 'AM', 'dialing_code' => '+374'],
            ['name' => 'Angola', 'code' => 'AO', 'dialing_code' => '+244'],
            ['name' => 'Argentina', 'code' => 'AR', 'dialing_code' => '+54'],
            ['name' => 'Austria', 'code' => 'AT', 'dialing_code' => '+43'],
            ['name' => 'Australia', 'code' => 'AU', 'dialing_code' => '+61'],
            ['name' => 'Aruba', 'code' => 'AW', 'dialing_code' => '+297'],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'dialing_code' => '+994'],
            ['name' => 'Barbados', 'code' => 'BB', 'dialing_code' => '+1246'],
            ['name' => 'Bangladesh', 'code' => 'BD', 'dialing_code' => '+880'],
            ['name' => 'Belgium', 'code' => 'BE', 'dialing_code' => '+32'],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'dialing_code' => '+226'],
            ['name' => 'Bulgaria', 'code' => 'BG', 'dialing_code' => '+359'],
            ['name' => 'Bahrain', 'code' => 'BH', 'dialing_code' => '+973'],
            ['name' => 'Burundi', 'code' => 'BI', 'dialing_code' => '+257'],
            ['name' => 'Benin', 'code' => 'BJ', 'dialing_code' => '+229'],
            ['name' => 'Bermuda', 'code' => 'BM', 'dialing_code' => '+1441'],
            ['name' => 'Bolivia', 'code' => 'BO', 'dialing_code' => '+591'],
            ['name' => 'Brazil', 'code' => 'BR', 'dialing_code' => '+55'],
            ['name' => 'Bhutan', 'code' => 'BT', 'dialing_code' => '+975'],
            ['name' => 'Botswana', 'code' => 'BW', 'dialing_code' => '+267'],
            ['name' => 'Belarus', 'code' => 'BY', 'dialing_code' => '+375'],
            ['name' => 'Belize', 'code' => 'BZ', 'dialing_code' => '+501'],
            ['name' => 'Canada', 'code' => 'CA', 'dialing_code' => '+1'],
            ['name' => 'Central African Republic', 'code' => 'CF', 'dialing_code' => '+236'],
            ['name' => 'Congo', 'code' => 'CG', 'dialing_code' => '+242'],
            ['name' => 'Switzerland', 'code' => 'CH', 'dialing_code' => '+41'],
            ['name' => 'Cook Islands', 'code' => 'CK', 'dialing_code' => '+682'],
            ['name' => 'Chile', 'code' => 'CL', 'dialing_code' => '+56'],
            ['name' => 'Cameroon', 'code' => 'CM', 'dialing_code' => '+237'],
            ['name' => 'China', 'code' => 'CN', 'dialing_code' => '+86'],
            ['name' => 'Colombia', 'code' => 'CO', 'dialing_code' => '+57'],
            ['name' => 'Costa Rica', 'code' => 'CR', 'dialing_code' => '+506'],
            ['name' => 'Cuba', 'code' => 'CU', 'dialing_code' => '+53'],
            ['name' => 'Cape Verde', 'code' => 'CV', 'dialing_code' => '+238'],
            ['name' => 'Curaçao', 'code' => 'CW', 'dialing_code' => '+5999'],
            ['name' => 'Cyprus', 'code' => 'CY', 'dialing_code' => '+357'],
            ['name' => 'Czech Republic', 'code' => 'CZ', 'dialing_code' => '+420'],
            ['name' => 'Germany', 'code' => 'DE', 'dialing_code' => '+49'],
            ['name' => 'Djibouti', 'code' => 'DJ', 'dialing_code' => '+253'],
            ['name' => 'Denmark', 'code' => 'DK', 'dialing_code' => '+45'],
            ['name' => 'Dominica', 'code' => 'DM', 'dialing_code' => '+1767'],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'dialing_code' => '+1'],
            ['name' => 'Algeria', 'code' => 'DZ', 'dialing_code' => '+213'],
            ['name' => 'Ecuador', 'code' => 'EC', 'dialing_code' => '+593'],
            ['name' => 'Estonia', 'code' => 'EE', 'dialing_code' => '+372'],
            ['name' => 'Egypt', 'code' => 'EG', 'dialing_code' => '+20'],
            ['name' => 'Spain', 'code' => 'ES', 'dialing_code' => '+34'],
            ['name' => 'Ethiopia', 'code' => 'ET', 'dialing_code' => '+251'],
            ['name' => 'Finland', 'code' => 'FI', 'dialing_code' => '+358'],
            ['name' => 'Fiji', 'code' => 'FJ', 'dialing_code' => '+679'],
            ['name' => 'Falkland Islands', 'code' => 'FK', 'dialing_code' => '+500'],
            ['name' => 'Faroe Islands', 'code' => 'FO', 'dialing_code' => '+298'],
            ['name' => 'France', 'code' => 'FR', 'dialing_code' => '+33'],
            ['name' => 'Gabon', 'code' => 'GA', 'dialing_code' => '+241'],
            ['name' => 'United Kingdom', 'code' => 'GB', 'dialing_code' => '+44'],
            ['name' => 'Grenada', 'code' => 'GD', 'dialing_code' => '+1473'],
            ['name' => 'Georgia', 'code' => 'GE', 'dialing_code' => '+995'],
            ['name' => 'French Guiana', 'code' => 'GF', 'dialing_code' => '+594'],
            ['name' => 'Guernsey', 'code' => 'GG', 'dialing_code' => '+44'],
            ['name' => 'Ghana', 'code' => 'GH', 'dialing_code' => '+233'],
            ['name' => 'Gibraltar', 'code' => 'GI', 'dialing_code' => '+350'],
            ['name' => 'Greenland', 'code' => 'GL', 'dialing_code' => '+299'],
            ['name' => 'Gambia', 'code' => 'GM', 'dialing_code' => '+220'],
            ['name' => 'Guinea', 'code' => 'GN', 'dialing_code' => '+224'],
            ['name' => 'Guadeloupe', 'code' => 'GP', 'dialing_code' => '+590'],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'dialing_code' => '+240'],
            ['name' => 'Greece', 'code' => 'GR', 'dialing_code' => '+30'],
            ['name' => 'Guatemala', 'code' => 'GT', 'dialing_code' => '+502'],
            ['name' => 'Guam', 'code' => 'GU', 'dialing_code' => '+1671'],
            ['name' => 'Guyana', 'code' => 'GY', 'dialing_code' => '+592'],
            ['name' => 'Honduras', 'code' => 'HN', 'dialing_code' => '+504'],
            ['name' => 'Croatia', 'code' => 'HR', 'dialing_code' => '+385'],
            ['name' => 'Haiti', 'code' => 'HT', 'dialing_code' => '+509'],
            ['name' => 'Hungary', 'code' => 'HU', 'dialing_code' => '+36'],
            ['name' => 'Indonesia', 'code' => 'ID', 'dialing_code' => '+62'],
            ['name' => 'Ireland', 'code' => 'IE', 'dialing_code' => '+353'],
            ['name' => 'Israel', 'code' => 'IL', 'dialing_code' => '+972'],
            ['name' => 'Isle of Man', 'code' => 'IM', 'dialing_code' => '+44'],
            ['name' => 'India', 'code' => 'IN', 'dialing_code' => '+91'],
            ['name' => 'Iraq', 'code' => 'IQ', 'dialing_code' => '+964'],
            ['name' => 'Iran', 'code' => 'IR', 'dialing_code' => '+98'],
            ['name' => 'Iceland', 'code' => 'IS', 'dialing_code' => '+354'],
            ['name' => 'Italy', 'code' => 'IT', 'dialing_code' => '+39'],
            ['name' => 'Jersey', 'code' => 'JE', 'dialing_code' => '+44'],
            ['name' => 'Jamaica', 'code' => 'JM', 'dialing_code' => '+1876'],
            ['name' => 'Jordan', 'code' => 'JO', 'dialing_code' => '+962'],
            ['name' => 'Japan', 'code' => 'JP', 'dialing_code' => '+81'],
            ['name' => 'Kenya', 'code' => 'KE', 'dialing_code' => '+254'],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'dialing_code' => '+996'],
            ['name' => 'Cambodia', 'code' => 'KH', 'dialing_code' => '+855'],
            ['name' => 'Comoros', 'code' => 'KM', 'dialing_code' => '+269'],
            ['name' => 'Kuwait', 'code' => 'KW', 'dialing_code' => '+965'],
            ['name' => 'Cayman Islands', 'code' => 'KY', 'dialing_code' => '+1345'],
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'dialing_code' => '+7'],
            ['name' => 'Lebanon', 'code' => 'LB', 'dialing_code' => '+961'],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'dialing_code' => '+423'],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'dialing_code' => '+94'],
            ['name' => 'Liberia', 'code' => 'LR', 'dialing_code' => '+231'],
            ['name' => 'Lesotho', 'code' => 'LS', 'dialing_code' => '+266'],
            ['name' => 'Lithuania', 'code' => 'LT', 'dialing_code' => '+370'],
            ['name' => 'Luxembourg', 'code' => 'LU', 'dialing_code' => '+352'],
            ['name' => 'Latvia', 'code' => 'LV', 'dialing_code' => '+371'],
            ['name' => 'Libya', 'code' => 'LY', 'dialing_code' => '+218'],
            ['name' => 'Morocco', 'code' => 'MA', 'dialing_code' => '+212'],
            ['name' => 'Moldova', 'code' => 'MD', 'dialing_code' => '+373'],
            ['name' => 'Montenegro', 'code' => 'ME', 'dialing_code' => '+382'],
            ['name' => 'Madagascar', 'code' => 'MG', 'dialing_code' => '+261'],
            ['name' => 'Macedonia', 'code' => 'MK', 'dialing_code' => '+389'],
            ['name' => 'Mali', 'code' => 'ML', 'dialing_code' => '+223'],
            ['name' => 'Myanmar', 'code' => 'MM', 'dialing_code' => '+95'],
            ['name' => 'Mongolia', 'code' => 'MN', 'dialing_code' => '+976'],
            ['name' => 'Macau', 'code' => 'MO', 'dialing_code' => '+853'],
            ['name' => 'Martinique', 'code' => 'MQ', 'dialing_code' => '+596'],
            ['name' => 'Mauritania', 'code' => 'MR', 'dialing_code' => '+222'],
            ['name' => 'Montserrat', 'code' => 'MS', 'dialing_code' => '+1664'],
            ['name' => 'Malta', 'code' => 'MT', 'dialing_code' => '+356'],
            ['name' => 'Mauritius', 'code' => 'MU', 'dialing_code' => '+230'],
            ['name' => 'Maldives', 'code' => 'MV', 'dialing_code' => '+960'],
            ['name' => 'Malawi', 'code' => 'MW', 'dialing_code' => '+265'],
            ['name' => 'Mexico', 'code' => 'MX', 'dialing_code' => '+52'],
            ['name' => 'Malaysia', 'code' => 'MY', 'dialing_code' => '+60'],
            ['name' => 'Mozambique', 'code' => 'MZ', 'dialing_code' => '+258'],
            ['name' => 'Namibia', 'code' => 'NA', 'dialing_code' => '+264'],
            ['name' => 'New Caledonia', 'code' => 'NC', 'dialing_code' => '+687'],
            ['name' => 'Niger', 'code' => 'NE', 'dialing_code' => '+227'],
            ['name' => 'Nigeria', 'code' => 'NG', 'dialing_code' => '+234'],
            ['name' => 'Nicaragua', 'code' => 'NI', 'dialing_code' => '+505'],
            ['name' => 'Norway', 'code' => 'NO', 'dialing_code' => '+47'],
            ['name' => 'Nepal', 'code' => 'NP', 'dialing_code' => '+977'],
            ['name' => 'Nauru', 'code' => 'NR', 'dialing_code' => '+674'],
            ['name' => 'New Zealand', 'code' => 'NZ', 'dialing_code' => '+64'],
            ['name' => 'Oman', 'code' => 'OM', 'dialing_code' => '+968'],
            ['name' => 'Panama', 'code' => 'PA', 'dialing_code' => '+507'],
            ['name' => 'Peru', 'code' => 'PE', 'dialing_code' => '+51'],
            ['name' => 'French Polynesia', 'code' => 'PF', 'dialing_code' => '+689'],
            ['name' => 'Papua New Guinea', 'code' => 'PG', 'dialing_code' => '+675'],
            ['name' => 'Philippines', 'code' => 'PH', 'dialing_code' => '+63'],
            ['name' => 'Pakistan', 'code' => 'PK', 'dialing_code' => '+92'],
            ['name' => 'Poland', 'code' => 'PL', 'dialing_code' => '+48'],
            ['name' => 'Puerto Rico', 'code' => 'PR', 'dialing_code' => '+1'],
            ['name' => 'Portugal', 'code' => 'PT', 'dialing_code' => '+351'],
            ['name' => 'Paraguay', 'code' => 'PY', 'dialing_code' => '+595'],
            ['name' => 'Qatar', 'code' => 'QA', 'dialing_code' => '+974'],
            ['name' => 'Réunion', 'code' => 'RE', 'dialing_code' => '+262'],
            ['name' => 'Romania', 'code' => 'RO', 'dialing_code' => '+40'],
            ['name' => 'Serbia', 'code' => 'RS', 'dialing_code' => '+381'],
            ['name' => 'Rwanda', 'code' => 'RW', 'dialing_code' => '+250'],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'dialing_code' => '+966'],
            ['name' => 'Solomon Islands', 'code' => 'SB', 'dialing_code' => '+677'],
            ['name' => 'Seychelles', 'code' => 'SC', 'dialing_code' => '+248'],
            ['name' => 'Sudan', 'code' => 'SD', 'dialing_code' => '+249'],
            ['name' => 'Sweden', 'code' => 'SE', 'dialing_code' => '+46'],
            ['name' => 'Singapore', 'code' => 'SG', 'dialing_code' => '+65'],
            ['name' => 'Slovenia', 'code' => 'SI', 'dialing_code' => '+386'],
            ['name' => 'Slovakia', 'code' => 'SK', 'dialing_code' => '+421'],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'dialing_code' => '+232'],
            ['name' => 'San Marino', 'code' => 'SM', 'dialing_code' => '+378'],
            ['name' => 'Senegal', 'code' => 'SN', 'dialing_code' => '+221'],
            ['name' => 'Somalia', 'code' => 'SO', 'dialing_code' => '+252'],
            ['name' => 'Suriname', 'code' => 'SR', 'dialing_code' => '+597'],
            ['name' => 'El Salvador', 'code' => 'SV', 'dialing_code' => '+503'],
            ['name' => 'Syria', 'code' => 'SY', 'dialing_code' => '+963'],
            ['name' => 'Swaziland', 'code' => 'SZ', 'dialing_code' => '+268'],
            ['name' => 'Turks and Caicos Islands', 'code' => 'TC', 'dialing_code' => '+1649'],
            ['name' => 'Chad', 'code' => 'TD', 'dialing_code' => '+235'],
            ['name' => 'Togo', 'code' => 'TG', 'dialing_code' => '+228'],
            ['name' => 'Thailand', 'code' => 'TH', 'dialing_code' => '+66'],
            ['name' => 'Tajikistan', 'code' => 'TJ', 'dialing_code' => '+992'],
            ['name' => 'Turkmenistan', 'code' => 'TM', 'dialing_code' => '+993'],
            ['name' => 'Tunisia', 'code' => 'TN', 'dialing_code' => '+216'],
            ['name' => 'Turkey', 'code' => 'TR', 'dialing_code' => '+90'],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'dialing_code' => '+1868'],
            ['name' => 'Taiwan', 'code' => 'TW', 'dialing_code' => '+886'],
            ['name' => 'Tanzania', 'code' => 'TZ', 'dialing_code' => '+255'],
            ['name' => 'Ukraine', 'code' => 'UA', 'dialing_code' => '+380'],
            ['name' => 'Uganda', 'code' => 'UG', 'dialing_code' => '+256'],
            ['name' => 'United States', 'code' => 'US', 'dialing_code' => '+1'],
            ['name' => 'Uruguay', 'code' => 'UY', 'dialing_code' => '+598'],
            ['name' => 'Uzbekistan', 'code' => 'UZ', 'dialing_code' => '+998'],
            ['name' => 'Venezuela', 'code' => 'VE', 'dialing_code' => '+58'],
            ['name' => 'Vietnam', 'code' => 'VN', 'dialing_code' => '+84'],
            ['name' => 'Vanuatu', 'code' => 'VU', 'dialing_code' => '+678'],
            ['name' => 'Yemen', 'code' => 'YE', 'dialing_code' => '+967'],
            ['name' => 'South Africa', 'code' => 'ZA', 'dialing_code' => '+27'],
            ['name' => 'Zambia', 'code' => 'ZM', 'dialing_code' => '+260'],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'dialing_code' => '+263'],
        ];

        foreach ($countries as $country) {
            \App\Models\Country::factory()->create($country);
        }
    }
}
