<?php

namespace Database\Seeders;

use App\Models\Country;
use App\Models\Location;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $locations = [
            [
                'name' => 'Dakar',
                'slug' => 'dakar',
                'child' => [
                    ['name' => 'Cambérène', 'slug' => 'camberene'],
                    ['name' => 'Parcelles Assainies', 'slug' => 'parcelles-assainies'],
                    ['name' => 'Ngor', 'slug' => 'ngor'],
                    ['name' => 'Yoff', 'slug' => 'yoff'],
                    ['name' => 'Patte d‘oie', 'slug' => 'patte-doie'],
                    ['name' => 'Grand-Yoff', 'slug' => 'grand-yoff'],
                    ['name' => 'Sicap Liberté', 'slug' => 'sicap-liberte'],
                    ['name' => 'Ouakam', 'slug' => 'ouakam'],
                    ['name' => 'Dieuppeul', 'slug' => 'dieuppeul-derkle'],
                    ['name' => 'Hlm', 'slug' => 'hlm'],
                    ['name' => 'Biscuiterie', 'slug' => 'biscuiterie'],
                    ['name' => 'Grand-Dakar', 'slug' => 'grand-dakar'],
                    ['name' => 'Hann Bel-Air', 'slug' => 'hann-bel-air'],
                    ['name' => 'Mermoz', 'slug' => 'mermoz-sacre-coeur'],
                    ['name' => 'Gueule-Tapée', 'slug' => 'gueule-tapee-fass-colobane'],
                    ['name' => 'Médina', 'slug' => 'medina'],
                    ['name' => 'Plateau', 'slug' => 'plateau'],
                    ['name' => 'Gorée', 'slug' => 'goree'],
                    ['name' => 'Fann', 'slug' => 'fann-point-e-amitie'],
                    ['name' => 'Pikine', 'slug' => 'pikine'],
                    ['name' => 'Rufisque', 'slug' => 'rufisque'],
                    ['name' => 'Guediawaye', 'slug' => 'guediawaye'],
                    ['name' => 'Keur Massar', 'slug' => 'keur-massar'],
                    ['name' => 'Kounoune', 'slug' => 'kounoune'],
                    ['name' => 'Bambilor', 'slug' => 'bambilor'],
                    ['name' => 'Ndiakhirate', 'slug' => 'ndiakhirate'],
                    ['name' => 'Sangalkam', 'slug' => 'sangalkam'],
                    ['name' => 'Mbao', 'slug' => 'mbao'],
                    ['name' => 'Almadies', 'slug' => 'almadies'],
                    ['name' => 'Virage', 'slug' => 'virage'],
                    ['name' => 'Ouest foire', 'slug' => 'ouest-foire'],
                    ['name' => 'Nord foire', 'slug' => 'nord-foire'],
                    ['name' => 'Djily mbaye', 'slug' => 'djily-mbaye'],
                    ['name' => 'Thongor', 'slug' => 'thongor'],
                    ['name' => 'Sud foire', 'slug' => 'sud-foire'],
                    ['name' => 'Sicap foire', 'slug' => 'sicap-foire'],
                    ['name' => 'Hlm grand-yoff', 'slug' => 'hlm-grand-yoff'],
                    ['name' => 'Liberte 1', 'slug' => 'liberte-1'],
                    ['name' => 'Liberte 2', 'slug' => 'liberte-2'],
                    ['name' => 'Liberte 3', 'slug' => 'liberte-3'],
                    ['name' => 'Liberte 4', 'slug' => 'liberte-4'],
                    ['name' => 'Liberte 6', 'slug' => 'liberte-6'],
                    ['name' => 'Liberte 6 extension', 'slug' => 'liberte-6-extension'],
                    ['name' => 'Liberte 5', 'slug' => 'liberte-5'],
                    ['name' => 'Mamelles', 'slug' => 'mamelles'],
                    ['name' => 'Comico', 'slug' => 'comico'],
                    ['name' => 'Cité avion', 'slug' => 'cite-avion'],
                    ['name' => 'Cité asecna', 'slug' => 'cite-asecna'],
                    ['name' => 'Cité assemblée', 'slug' => 'cite-assemblee'],
                    ['name' => 'Derkle', 'slug' => 'derkle'],
                    ['name' => 'Hann maristes', 'slug' => 'hann-maristes'],
                    ['name' => 'Bel air', 'slug' => 'bel-air'],
                    ['name' => 'Zone industrielle', 'slug' => 'zone-industrielle'],
                    ['name' => 'Hann marinas', 'slug' => 'hann-marinas'],
                    ['name' => 'Sacré-cœur', 'slug' => 'sacre-coeur'],
                    ['name' => 'Sicap Sacré-cœur', 'slug' => 'sicap-sacre-coeur'],
                    ['name' => 'Cité keur gorgui', 'slug' => 'cite-keur-gorgui'],
                    ['name' => 'Sicap baobab', 'slug' => 'sicap-baobab'],
                    ['name' => 'Fenêtre mermoz', 'slug' => 'fenetre-mermoz'],
                    ['name' => 'Point-e', 'slug' => 'point-e'],
                    ['name' => 'Amitié', 'slug' => 'amitie'],
                    ['name' => 'Karack', 'slug' => 'karack'],
                    ['name' => 'Colobane', 'slug' => 'colobane'],
                    ['name' => 'Gibraltar', 'slug' => 'gibraltar'],
                    ['name' => 'Thiaroye', 'slug' => 'thiaroye'],
                    ['name' => 'Diamaguene', 'slug' => 'diamaguene'],
                    ['name' => 'Sicap mbao', 'slug' => 'sicap-mbao'],
                    ['name' => 'Dalifort', 'slug' => 'dalifort'],
                    ['name' => 'Djidah thiaroye kaw', 'slug' => 'djidah-thiaroye-kaw'],
                    ['name' => 'Guinaw rail', 'slug' => 'guinaw-rail'],
                    ['name' => 'Malika', 'slug' => 'malika'],
                    ['name' => 'Yeumbeul', 'slug' => 'yeumbeul'],
                    ['name' => 'Bargny', 'slug' => 'bargny'],
                    ['name' => 'Sebikotane', 'slug' => 'sebikotane'],
                    ['name' => 'Diamniadio', 'slug' => 'diamniadio'],
                    ['name' => 'Niakoul rap', 'slug' => 'niakoul-rap'],
                    ['name' => 'Sendou', 'slug' => 'sendou'],
                    ['name' => 'Toubab dialo', 'slug' => 'toubab-dialo'],
                    ['name' => 'Lac rose', 'slug' => 'lac-rose'],
                    ['name' => 'Yene', 'slug' => 'yene'],
                    ['name' => 'Tivaouane peulh', 'slug' => 'tivaouane-peulh'],
                    ['name' => 'Keur ndiaye lô', 'slug' => 'keur-ndiaye-lo'],
                    ['name' => 'Golf', 'slug' => 'golf'],
                    ['name' => 'Cité biagui', 'slug' => 'cite-biagui'],
                    ['name' => 'VDN', 'slug' => 'vdn'],
                    ['name' => 'Zone de captage', 'slug' => 'zone-de-captage'],
                    ['name' => 'Castor', 'slug' => 'castor'],
                    ['name' => 'Zac Mbao', 'slug' => 'zac-mbao'],
                    ['name' => 'Almadies 2', 'slug' => 'almadies-2'],
                    ['name' => 'Cité Damel', 'slug' => 'cite-damel'],
                    ['name' => 'Niague', 'slug' => 'niague'],
                    ['name' => 'Gorom', 'slug' => 'gorom'],
                    ['name' => 'Cite Mixta', 'slug' => 'cite-mixta'],
                    ['name' => 'Avenue Bourguiba', 'slug' => 'avenue-bourguiba'],
                    ['name' => 'Noflaye', 'slug' => 'noflaye'],
                    ['name' => 'Fann Hock', 'slug' => 'fann-hock'],
                    ['name' => 'Fass', 'slug' => 'fass'],
                    ['name' => 'Bayakh', 'slug' => 'bayakh'],
                    ['name' => 'vdn 3', 'slug' => 'vdn-3'],
                    ['name' => 'cité magistrat', 'slug' => 'cite-magistrat'],
                    ['name' => 'Corniche', 'slug' => 'corniche'],
                ],
            ],
            [
                'name' => 'Diourbel',
                'slug' => 'diourbel',
                'child' => [
                    ['name' => 'Mbacke', 'slug' => 'mbacke'],
                    ['name' => 'Bambey', 'slug' => 'bambey'],
                    ['name' => 'Touba', 'slug' => 'touba'],
                ],
            ],
            [
                'name' => 'Fatick',
                'slug' => 'fatick',
                'child' => [
                    ['name' => 'Foundiougne', 'slug' => 'foundiougne'],
                    ['name' => 'Toubacouta', 'slug' => 'toubacouta'],
                    ['name' => 'Djilor', 'slug' => 'djilor'],
                    ['name' => 'Diofior', 'slug' => 'diofior'],
                    ['name' => 'Soum', 'slug' => 'soum'],
                    ['name' => 'Karang Poste', 'slug' => 'karang-poste'],
                    ['name' => 'Passi', 'slug' => 'passi'],
                    ['name' => 'Gossas', 'slug' => 'gossas'],
                    ['name' => 'Sokone', 'slug' => 'sokone'],
                ],
            ],
            [
                'name' => 'Kaolack',
                'slug' => 'kaolack',
                'child' => [
                    ['name' => 'Ndoffane', 'slug' => 'ndoffane'],
                    ['name' => 'Nioro Du Rip', 'slug' => 'nioro-du-rip'],
                    ['name' => 'Keur Madiabel', 'slug' => 'keur-madiabel'],
                    ['name' => 'Sibassor', 'slug' => 'sibassor'],
                    ['name' => 'Fass', 'slug' => 'fass-kaolack'],
                    ['name' => 'Guinguineo', 'slug' => 'guinguineo'],
                    ['name' => 'Mboss', 'slug' => 'mboss'],
                    ['name' => 'Kahone', 'slug' => 'kahone'],
                    ['name' => 'Gandiaye', 'slug' => 'gandiaye'],
                ],
            ],
            [
                'name' => 'Kolda',
                'slug' => 'kolda',
                'child' => [
                    ['name' => 'Velingara', 'slug' => 'velingara'],
                    ['name' => 'Dabo', 'slug' => 'dabo'],
                    ['name' => 'Kounkane', 'slug' => 'kounkane'],
                    ['name' => 'Diaobe Kabendou', 'slug' => 'diaobe-kabendou'],
                    ['name' => 'Medina Yoro Foulah', 'slug' => 'medina-yoro-foulah'],
                    ['name' => 'Salikegne', 'slug' => 'salikegne'],
                    ['name' => 'Sare Yoba Diega', 'slug' => 'sare-yoba-diega'],
                    ['name' => 'Pata', 'slug' => 'pata'],
                ],
            ],
            [
                'name' => 'Louga',
                'slug' => 'louga',
                'child' => [
                    ['name' => 'Mbeuleukhe', 'slug' => 'mbeuleukhe'],
                    ['name' => 'Gueoul', 'slug' => 'gueoul'],
                    ['name' => 'Kebemer', 'slug' => 'kebemer'],
                    ['name' => 'Dahra', 'slug' => 'dahra'],
                    ['name' => 'Linguere', 'slug' => 'linguere'],
                    ['name' => 'Leona', 'slug' => 'leona'],
                    ['name' => 'Ngueune Sarr', 'slug' => 'ngueune-sarr'],
                    ['name' => 'Sakal', 'slug' => 'sakal'],
                ],
            ],
            [
                'name' => 'Matam',
                'slug' => 'matam',
                'child' => [
                    ['name' => 'Dembancane', 'slug' => 'dembancane'],
                    ['name' => 'Hamadi Hounare', 'slug' => 'hamadi-hounare'],
                    ['name' => 'Kanel', 'slug' => 'kanel'],
                    ['name' => 'Odobere', 'slug' => 'odobere'],
                    ['name' => 'Ouaounde', 'slug' => 'ouaounde'],
                    ['name' => 'Semme', 'slug' => 'semme'],
                    ['name' => 'Sinthiou Bamambe Banadji', 'slug' => 'sinthiou-bamambe-banadji'],
                    ['name' => 'Nguidjilone', 'slug' => 'nguidjilone'],
                    ['name' => 'Ourossogui', 'slug' => 'ourossogui'],
                    ['name' => 'Thilogne', 'slug' => 'thilogne'],
                    ['name' => 'Ranerou', 'slug' => 'ranerou'],
                ],
            ],
            [
                'name' => 'Saint-Louis',
                'slug' => 'saint-louis',
                'child' => [
                    ['name' => 'Gnith', 'slug' => 'gnith'],
                    ['name' => 'Dagana', 'slug' => 'dagana'],
                    ['name' => 'Gae', 'slug' => 'gae'],
                    ['name' => 'Ndombo Sandjiry', 'slug' => 'ndombo-sandjiry'],
                    ['name' => 'Richard Toll', 'slug' => 'richard-toll'],
                    ['name' => 'Ross Bethio', 'slug' => 'ross-bethio'],
                    ['name' => 'Rosso Senegal', 'slug' => 'rosso-senegal'],
                    ['name' => 'Aere Lao', 'slug' => 'aere-lao'],
                    ['name' => 'Bode Lao', 'slug' => 'bode-lao'],
                    ['name' => 'Demette', 'slug' => 'demette'],
                    ['name' => 'Galoya Toucouleur', 'slug' => 'galoya-toucouleur'],
                    ['name' => 'Gollere', 'slug' => 'gollere'],
                    ['name' => 'Guede Chantier', 'slug' => 'guede-chantier'],
                    ['name' => 'Mboumba', 'slug' => 'mboumba'],
                    ['name' => 'Ndioum', 'slug' => 'ndioum'],
                    ['name' => 'Niandane', 'slug' => 'niandane'],
                    ['name' => 'Pete', 'slug' => 'pete'],
                    ['name' => 'Podor', 'slug' => 'podor'],
                    ['name' => 'Walalde', 'slug' => 'walalde'],
                    ['name' => 'Mpal', 'slug' => 'mpal'],
                ],
            ],
            [
                'name' => 'Tambacounda',
                'slug' => 'tambacounda',
                'child' => [
                    ['name' => 'Bakel', 'slug' => 'bakel'],
                    ['name' => 'Diawara', 'slug' => 'diawara'],
                    ['name' => 'Kidira', 'slug' => 'kidira'],
                    ['name' => 'Goudiry', 'slug' => 'goudiry'],
                    ['name' => 'Kothiary', 'slug' => 'kothiary'],
                    ['name' => 'Mereto', 'slug' => 'mereto'],
                    ['name' => 'Koumpentoum', 'slug' => 'koumpentoum'],
                    ['name' => 'Maleme Niani', 'slug' => 'maleme-niani'],
                ],
            ],
            [
                'name' => 'Thiès',
                'slug' => 'thies',
                'child' => [
                    ['name' => 'Sandiara', 'slug' => 'sandiara'],
                    ['name' => 'Joal Fadiouth', 'slug' => 'joal-fadiouth'],
                    ['name' => 'Mbour', 'slug' => 'mbour'],
                    ['name' => 'Ngaparou', 'slug' => 'ngaparou'],
                    ['name' => 'Nguekhokh', 'slug' => 'nguekhokh'],
                    ['name' => 'Popenguine', 'slug' => 'popenguine'],
                    ['name' => 'Saly Portudal', 'slug' => 'saly-portudal'],
                    ['name' => 'Somone', 'slug' => 'somone'],
                    ['name' => 'Thiadiaye', 'slug' => 'thiadiaye'],
                    ['name' => 'Kayar', 'slug' => 'kayar'],
                    ['name' => 'Khombole', 'slug' => 'khombole'],
                    ['name' => 'Pout', 'slug' => 'pout'],
                    ['name' => 'Pambal', 'slug' => 'pambal'],
                    ['name' => 'Mboro', 'slug' => 'mboro'],
                    ['name' => 'Meckhe', 'slug' => 'meckhe'],
                    ['name' => 'Tivaouane', 'slug' => 'tivaouane'],
                    ['name' => 'Nianing', 'slug' => 'nianing'],
                    ['name' => 'Nguering', 'slug' => 'nguering'],
                    ['name' => 'Warang', 'slug' => 'warang'],
                    ['name' => 'Pointe Sarene', 'slug' => 'pointe-sarene'],
                    ['name' => 'Mbodiene', 'slug' => 'mbodiene'],
                    ['name' => 'Guereo', 'slug' => 'guereo'],
                    ['name' => 'Toubab Dialaw', 'slug' => 'toubab-dialaw'],
                    ['name' => 'Diass', 'slug' => 'diass'],
                    ['name' => 'Fissel', 'slug' => 'fissel'],
                    ['name' => 'Malicounda', 'slug' => 'malicounda'],
                    ['name' => 'Ndiaganiao', 'slug' => 'ndiaganiao'],
                    ['name' => 'Ngueniene', 'slug' => 'ngueniene'],
                    ['name' => 'Sessene', 'slug' => 'sessene'],
                    ['name' => 'Sindia', 'slug' => 'sindia'],
                    ['name' => 'Saly', 'slug' => 'saly'],
                    ['name' => 'Diender', 'slug' => 'diender'],
                    ['name' => 'Fandene', 'slug' => 'fandene'],
                    ['name' => 'Keur moussa', 'slug' => 'keur-moussa'],
                    ['name' => 'Ngoundiane', 'slug' => 'ngoundiane'],
                    ['name' => 'Notto', 'slug' => 'notto'],
                    ['name' => 'Tassette', 'slug' => 'tassette'],
                    ['name' => 'Thienaba', 'slug' => 'thienaba'],
                    ['name' => 'Touba toul', 'slug' => 'touba-toul'],
                    ['name' => 'Pointe sarrene', 'slug' => 'pointe-sarrene'],
                    ['name' => 'Gandigal', 'slug' => 'gandigal'],
                    ['name' => 'Ndayane', 'slug' => 'ndayane'],
                ],
            ],
            [
                'name' => 'Ziguinchor',
                'slug' => 'ziguinchor',
                'child' => [
                    ['name' => 'Bignona', 'slug' => 'bignona'],
                    ['name' => 'Diouloulou', 'slug' => 'diouloulou'],
                    ['name' => 'Thionck Essyl', 'slug' => 'thionck-essyl'],
                    ['name' => 'Oussouye', 'slug' => 'oussouye'],
                    ['name' => 'Cap Skirring', 'slug' => 'cap-skirring'],
                ],
            ],
            [
                'name' => 'Sédhiou',
                'slug' => 'sedhiou',
                'child' => [
                    ['name' => 'Djinany', 'slug' => 'djinany'],
                    ['name' => 'Ndiamalathiel', 'slug' => 'ndiamalathiel'],
                    ['name' => 'Bounkiling', 'slug' => 'bounkiling'],
                    ['name' => 'Madina Wandifa', 'slug' => 'madina-wandifa'],
                    ['name' => 'Dioudoubou', 'slug' => 'dioudoubou'],
                    ['name' => 'Kaour', 'slug' => 'kaour'],
                    ['name' => 'Simbandi Brassou', 'slug' => 'simbandi-brassou'],
                    ['name' => 'Diattacounda', 'slug' => 'diattacounda'],
                    ['name' => 'Goudomp', 'slug' => 'goudomp'],
                    ['name' => 'Samine', 'slug' => 'samine'],
                    ['name' => 'Tanaff', 'slug' => 'tanaff'],
                    ['name' => 'Dianah Malary', 'slug' => 'dianah-malary'],
                    ['name' => 'Marssassoum', 'slug' => 'marssassoum'],
                ],
            ],
            [
                'name' => 'Kaffrine',
                'slug' => 'kaffrine',
                'child' => [
                    ['name' => 'Mabo', 'slug' => 'mabo'],
                    ['name' => 'Birkilane', 'slug' => 'birkilane'],
                    ['name' => 'Nganda', 'slug' => 'nganda'],
                    ['name' => 'Koungheul', 'slug' => 'koungheul'],
                    ['name' => 'Malem Hodar', 'slug' => 'malem-hodar'],
                ],
            ],
            [
                'name' => 'Kedougou',
                'slug' => 'kedougou',
                'child' => [
                    ['name' => 'Salemata', 'slug' => 'salemata'],
                    ['name' => 'Saraya', 'slug' => 'saraya'],
                ],
            ],
            [
                'name' => 'Sine saloum',
                'slug' => 'sine-saloum',
                'child' => [
                    ['name' => 'Palmarin', 'slug' => 'palmarin'],
                    ['name' => 'Djiffer', 'slug' => 'djiffer'],
                    ['name' => 'Dionevar', 'slug' => 'dionevar'],
                    ['name' => 'Ndangane', 'slug' => 'ndangane'],
                ],
            ],
            [
                'name' => 'Autres',
                'slug' => 'autres',
                'child' => [],
            ],
        ];

        $country = Country::query()->where('code', 'SN')->first();

        foreach ($locations as $regionData) {
            $region = Location::factory()->create([
                'country_id' => $country->id,
                'parent_id'  => null,
                'name'       => $regionData['name'],
                'slug'       => $regionData['slug'],
                'level'      => 0,
            ]);

            if (! empty($regionData['child'])) {
                foreach ($regionData['child'] as $childData) {
                    Location::factory()->create([
                        'country_id' => $country->id,
                        'parent_id'  => $region->id,
                        'name'       => $childData['name'],
                        'slug'       => $childData['slug'],
                        'level'      => 1,
                    ]);
                }
            }
        }
    }
}
